[package]
name = "qubit-command"
version = "0.6.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-command"
description = "Command-line process running utilities for Rust"
homepage = "https://github.com/qubit-ltd/rs-command"
documentation = "https://docs.rs/qubit-command"
readme = "README.md"
keywords = ["command", "process", "shell", "utility", "qubit"]
categories = ["command-line-utilities", "development-tools"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
    "/benches/**",
]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }

[lib]
name = "qubit_command"
doctest = true

[[bench]]
name = "command_runner"
harness = false

[dependencies]
log = "0.4"
process-wrap = { version = "9.1", default-features = false, features = ["std", "process-group", "job-object"] }
same-file = "1.0"
thiserror = "2.0"
qubit-clock = { version = "0.13" }
qubit-redact = { version = "0.5", path = "../rs-redact", default-features = false }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
criterion = { version = "0.8", default-features = false }
tempfile = "3.27"
qubit-clock = { version = "0.13", features = ["test-util"] }
