[package]
name = "qubit-command"
version = "0.6.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-command"
description = "Command-line process running utilities for Rust"
homepage = "https://github.com/qubit-ltd/rs-command"
documentation = "https://docs.rs/qubit-command"
readme = "README.md"
keywords = ["command", "process", "shell", "utility", "qubit"]
categories = ["command-line-utilities", "development-tools"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_command"
doctest = true

[dependencies]
log = "0.4"
process-wrap = { version = "9.1", default-features = false, features = ["std", "process-group", "job-object"] }
qubit-clock = { version = "0.10", path = "../rs-clock" }
qubit-redact = { version = "0.3", path = "../rs-redact", default-features = false }
same-file = "1.0"
thiserror = "2.0"

[dev-dependencies]
qubit-local-files = { path = "../rs-local-files", version = "0.7" }
